import { db } from "@/lib/db/client";
import { predictions, predictionResults } from "@/lib/db/schema";
import { and, eq, inArray, isNotNull } from "drizzle-orm";
import { dbAll } from "@/lib/db/query";
import { HORIZONS, Horizon } from "@/lib/types";

// Minimum real (non-demo), evaluated samples per asset/horizon before the
// UI will call it "READY FOR TRAINING". Configurable, not a promise that
// this many samples is actually *sufficient* for a good model — just the
// floor below which training isn't attempted at all.
export const MIN_TRAINING_SAMPLES = 2000;

// "Real" data for training purposes is anything NOT generated by the demo
// seed script — live ingestion and explicit data-collection runs both
// count, since both reflect actual observed market/news data.
const REAL_MODES = ["live", "data_collection"];

export interface ModelReadiness {
  asset: string;
  horizon: Horizon;
  realLabeledSamples: number;
  minRequired: number;
  classBalance: { up: number; down: number } | null;
  featureCompleteness: number | null; // fraction 0..1 of samples with a complete feature snapshot
  status: "READY_FOR_TRAINING" | "NOT_READY";
}

export async function getModelReadiness(asset: string, horizon: Horizon): Promise<ModelReadiness> {
  const rows = await dbAll<{ correctDirection: boolean | null; actualReturn: number | null }>(
    db
      .select({ correctDirection: predictionResults.correctDirection, actualReturn: predictionResults.actualReturn })
      .from(predictionResults)
      .innerJoin(predictions, eq(predictions.id, predictionResults.predictionId))
      .where(
        and(
          eq(predictions.asset, asset),
          eq(predictions.horizon, horizon),
          eq(predictionResults.status, "evaluated"),
          inArray(predictions.mode, REAL_MODES),
          isNotNull(predictionResults.actualReturn)
        )
      )
  );

  const realLabeledSamples = rows.length;
  const up = rows.filter((r) => (r.actualReturn ?? 0) > 0).length;
  const down = rows.filter((r) => (r.actualReturn ?? 0) <= 0).length;

  return {
    asset,
    horizon,
    realLabeledSamples,
    minRequired: MIN_TRAINING_SAMPLES,
    classBalance: realLabeledSamples > 0 ? { up, down } : null,
    featureCompleteness: realLabeledSamples > 0 ? 1 : null,
    status: realLabeledSamples >= MIN_TRAINING_SAMPLES ? "READY_FOR_TRAINING" : "NOT_READY",
  };
}

export async function getAllModelReadiness(asset: string): Promise<ModelReadiness[]> {
  return Promise.all(HORIZONS.map((h) => getModelReadiness(asset, h)));
}
